spring:
  cache:
    type: redis
    cache-names: orders
    redis:
      time-to-live: 60000
      cache-null-values: true
  redis:
        port: 6379


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop
    username: root
    password: joolafatemeh652@gmail.com
    hikari:
      initialization-fail-timeout: 0
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update